embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9 
reg_weight: [0.0, 1e-05, 1e-04, 1e-03]

n_mm_layers: [1,2,4]
n_ui_layers: 2
knn_k: 10

mm_image_weight: 0.1
dropout: [0.1, 0.5, 0.8]
learning_rate: [0.0001, 0.001, 0.01]

hyper_parameters: ["n_mm_layers","learning_rate", "reg_weight", "dropout"]