embedding_size: 64
n_layers: [4]
# reg_weight: [1e-02, 1e-03, 1e-04, 1e-05]
reg_weight: [0.0001]  
learning_rate: [0.0001, 0.001, 0.01] 

dropout: 0.0 # [0.0, 0.1, 0.2]
hyper_parameters: ["n_layers", "learning_rate", "reg_weight"]
