embedding_size: 64
n_layers: [1,2,4,8]
reg_weight: [0.00001, 0.0001, 0.001] # 0, 0.01, 0.1]
learning_rate: [0.0001, 0.0005, 0.001.0.005, 0.01]

hyper_parameters: ["learning_rate","reg_weight","n_layers"]
